const vocabularyData = [
    { word: "各执己见", pinyin: "gè zhí jǐ jiàn", defZh: "各人都坚持自己的意见，互不相让。", defEn: "Each sticks to their own view", defBm: "Masing-masing berpegang pada pendapat sendiri", example: "会议上大家各执己见，讨论了很久也没有结果。" },
    { word: "不欢而散", pinyin: "bù huān ér sàn", defZh: "很不愉快地分开。", defEn: "Part on bad terms", defBm: "Berpisah dengan tidak senang hati", example: "由于意见不合，这次的聚会最终不欢而散。" },
    { word: "蠢蠢欲动", pinyin: "chǔn chǔn yù dòng", defZh: "比喻敌人准备进攻或坏人策划破坏活动。", defEn: "Ready to make trouble / Stir into action", defBm: "Mula bergerak / Bersedia untuk bertindak", example: "敌军在边境蠢蠢欲动，我军必须严加防范。" },
    { word: "踌躇不前", pinyin: "chóu chú bù qián", defZh: "犹豫不决，不敢前进。", defEn: "Hesitate to move forward", defBm: "Teragak-agak untuk maju", example: "面对困难，他踌躇不前，失去了宝贵的机会。" },
    { word: "跃跃欲试", pinyin: "yuè yuè yù shì", defZh: "心情急切地想要试一试。", defEn: "Eager to try", defBm: "Tidak sabar untuk mencuba", example: "看到同学们都在比赛，他也跃跃欲试。" },
    { word: "寡不敌众", pinyin: "guǎ bù dí zhòng", defZh: "人少的一方抵挡不住人多的一方。", defEn: "The few cannot fight the many", defBm: "Yang sedikit tidak mampu melawan yang ramai", example: "虽然他们英勇作战，但寡不敌众，最终撤退了。" },
    { word: "信誓旦旦", pinyin: "xìn shì dàn dàn", defZh: "誓言说得非常诚恳、郑重。", defEn: "Pledge solemnly", defBm: "Bersumpah dengan bersungguh-sungguh", example: "他信誓旦旦地保证，一定会按时完成任务。" },
    { word: "池鱼之殃", pinyin: "chí yú zhī yāng", defZh: "比喻因牵连而遭受灾祸。", defEn: "Innocent bystander suffering / Collateral damage", defBm: "Musibah akibat terlibat", example: "两家公司打官司，害得供应商也遭受池鱼之殃。" },
    { word: "身怀六甲", pinyin: "shēn huái liù jiǎ", defZh: "指妇女怀孕。", defEn: "Pregnant", defBm: "Mengandung", example: "她身怀六甲，行动不便，同事们都很照顾她。" },
    { word: "仓皇失措", pinyin: "cāng huáng shī cuò", defZh: "匆忙慌张，不知道该怎么办。", defEn: "Panic-stricken / Confused", defBm: "Gegabah / Kelam kabut", example: "火灾发生时，他仓皇失措，不知道该往哪里跑。" },
    { word: "不拘小节", pinyin: "bù jū xiǎo jié", defZh: "不拘泥于细小的事情，形容人豪爽洒脱。", defEn: "Not bothered by trifles", defBm: "Tidak mengambil berat hal kecil", example: "他为人不拘小节，和朋友们相处得很融洽。" },
    { word: "百感交集", pinyin: "bǎi gǎn jiāo jí", defZh: "各种感触交织在一起，形容心情复杂。", defEn: "Mixed feelings", defBm: "Perasaan bercampur-baur", example: "站在母校门前，他百感交集，想起了许多往事。" },
    { word: "不耻下问", pinyin: "bù chǐ xià wèn", defZh: "不以向学问比自己低的人请教为耻。", defEn: "Not ashamed to ask and learn", defBm: "Tidak malu bertanya", example: "他谦虚好学，不耻下问，进步得非常快。" },
    { word: "名列前茅", pinyin: "míng liè qián máo", defZh: "名次排在前面，成绩优秀。", defEn: "Rank among the best", defBm: "Menduduki tempat teratas", example: "她学习认真，每次考试都名列前茅。" },
    { word: "敷衍了事", pinyin: "fū yǎn liǎo shì", defZh: "做事马虎，随便应付过去。", defEn: "Do things perfunctorily", defBm: "Melakukan kerja secara sambil lewa", example: "做作业要认真，不能敷衍了事。" },
    { word: "足智多谋", pinyin: "zú zhì duō móu", defZh: "形容人聪明机智，善于谋划。", defEn: "Wise and resourceful", defBm: "Bijak dan penuh akal", example: "诸葛亮足智多谋，是历史上有名的军师。" },
    { word: "误入歧途", pinyin: "wù rù qí tú", defZh: "错误地走上了邪路。", defEn: "Go astray / Take the wrong path", defBm: "Tersalah jalan / Terpesong", example: "在朋友的帮助下，他终于没有误入歧途。" },
    { word: "家喻户晓", pinyin: "jiā yù hù xiǎo", defZh: "每家每户都知道，形容人人皆知。", defEn: "Known to every household", defBm: "Diketahui oleh semua orang", example: "这个故事家喻户晓，连小孩子都能讲出来。" },
    { word: "映入眼帘", pinyin: "yìng rù yǎn lián", defZh: "出现在眼前，被眼睛看到。", defEn: "Come into view", defBm: "Terpandang di mata", example: "一打开门，美丽的景色便映入眼帘。" },
    { word: "东张西望", pinyin: "dōng zhāng xī wàng", defZh: "四处张望，形容注意力不集中。", defEn: "Look around / Glance left and right", defBm: "Melihat ke kiri dan ke kanan", example: "上课时要专心，不要东张西望。" },
    { word: "色彩缤纷", pinyin: "sè cǎi bīn fēn", defZh: "颜色繁多而鲜艳。", defEn: "Colorful / Vivid", defBm: "Warna-warni", example: "花园里色彩缤纷，美不胜收。" },
    { word: "惟妙惟肖", pinyin: "wéi miào wéi xiào", defZh: "形容描写或模仿得非常逼真。", defEn: "Remarkably true to life", defBm: "Sangat mirip / Tepat sekali", example: "他模仿老师说话，惟妙惟肖，逗得大家哈哈大笑。" },
    { word: "目不转睛", pinyin: "mù bù zhuǎn jīng", defZh: "眼睛一动不动地注视着。", defEn: "Gaze fixedly / Eyes glued to", defBm: "Memandang tanpa berkelip", example: "他目不转睛地看着表演，生怕错过任何精彩画面。" },
    { word: "哄堂大笑", pinyin: "hōng táng dà xiào", defZh: "满屋子的人同时大笑起来。", defEn: "The whole room bursts into laughter", defBm: "Seluruh dewan ketawa", example: "他的笑话太有趣了，全班同学哄堂大笑。" },
    { word: "合不拢嘴", pinyin: "hé bù lǒng zuǐ", defZh: "笑得嘴巴都合不上，形容非常高兴。", defEn: "Grin from ear to ear", defBm: "Tersenyum hingga tidak dapat menutup mulut", example: "听到自己得奖的消息，他高兴得合不拢嘴。" },
    { word: "身临其境", pinyin: "shēn lín qí jìng", defZh: "亲身到了那个境地。", defEn: "Personally experience the scene", defBm: "Mengalami sendiri", example: "这部电影拍得很逼真，让观众仿佛身临其境。" },
    { word: "活灵活现", pinyin: "huó líng huó xiàn", defZh: "形容描绘或模仿得非常生动逼真。", defEn: "Vivid / Lifelike", defBm: "Hidup / Nyata", example: "他画笔下的花鸟活灵活现，栩栩如生。" },
    { word: "目不暇给", pinyin: "mù bù xiá jǐ", defZh: "东西太多，眼睛来不及看。", defEn: "Too much to take in / Dazzled", defBm: "Terlalu banyak untuk dilihat", example: "展品琳琅满目，令人目不暇给。" },
    { word: "迫在眉睫", pinyin: "pò zài méi jié", defZh: "比喻事情非常紧迫，已在眼前。", defEn: "Extremely urgent / Imminent", defBm: "Sangat mendesak", example: "保护环境已经迫在眉睫，人人都应该行动起来。" },
    { word: "一扫而空", pinyin: "yī sǎo ér kōng", defZh: "一下子扫除干净，也形容东西被吃光或抢光。", defEn: "Sweep away completely / Clear out", defBm: "Dihabiskan / Dilenyapkan", example: "桌上的美食被大家一扫而空。" },
    { word: "截然不同", pinyin: "jié rán bù tóng", defZh: "完全不相同，差别很大。", defEn: "Completely different", defBm: "Sangat berbeza", example: "他们兄弟俩的性格截然不同。" },
    { word: "津津有味", pinyin: "jīn jīn yǒu wèi", defZh: "形容兴趣浓厚、很有滋味。", defEn: "With great relish / Enjoyably", defBm: "Dengan penuh minat", example: "他津津有味地读着这本小说，完全忘了时间。" },
    { word: "焕然一新", pinyin: "huàn rán yī xīn", defZh: "形容呈现出崭新的面貌。", defEn: "Look completely new / Take on a new look", defBm: "Kelihatan segar dan baru", example: "经过装修，老屋焕然一新，变得漂亮多了。" },
    { word: "唾手可得", pinyin: "tuò shǒu kě dé", defZh: "比喻非常容易得到。", defEn: "Easily obtainable / Within easy reach", defBm: "Mudah diperoleh", example: "只要再努力一点，冠军就唾手可得了。" },
    { word: "茅塞顿开", pinyin: "máo sè dùn kāi", defZh: "比喻突然理解、一下子想通了。", defEn: "Suddenly see the light / Enlightened", defBm: "Tiba-tiba faham", example: "听了老师的讲解，他茅塞顿开，终于明白了这道题的解法。" },
    { word: "如梦初醒", pinyin: "rú mèng chū xǐng", defZh: "好像刚从梦中醒来，比喻从糊涂中醒悟过来。", defEn: "As if awakening from a dream / Realize suddenly", defBm: "Seperti baru sedar dari mimpi", example: "经过一番劝导，他如梦初醒，决定改过自新。" },
    { word: "茶饭不思", pinyin: "chá fàn bù sī", defZh: "没有心思喝茶吃饭，形容心情忧郁。", defEn: "Lose appetite / Worried sick", defBm: "Hilang selera makan", example: "为了这件事，他整日茶饭不思。" },
    { word: "叫苦连天", pinyin: "jiào kǔ lián tiān", defZh: "不断地抱怨痛苦和困难。", defEn: "Complain bitterly", defBm: "Merayu-rayu / Mengadu", example: "连续加班让员工们叫苦连天。" },
    { word: "疮痍满目", pinyin: "chuāng yí mǎn mù", defZh: "到处是灾祸破坏的景象。", defEn: "Devastated / Ruined landscape", defBm: "Keadaan yang rosak", example: "地震过后，灾区疮痍满目，令人心酸。" },
    { word: "爱莫能助", pinyin: "ài mò néng zhù", defZh: "虽然同情，但没有能力帮忙。", defEn: "Willing but unable to help", defBm: "Berkeinginan tetapi tidak mampu", example: "我很想帮他，但实在爱莫能助。" },
    { word: "千钧一发", pinyin: "qiān jūn yī fà", defZh: "比喻情况极其危急。", defEn: "Critical moment / Life-and-death", defBm: "Keadaan genting", example: "在这千钧一发之际，消防员及时赶到，救出了被困的人。" },
    { word: "惊魂未定", pinyin: "jīng hún wèi dìng", defZh: "受惊后情绪还没有平复。", defEn: "Still in shock", defBm: "Masih terkejut", example: "他惊魂未定，坐在一旁久久说不出话来。" },
    { word: "危如累卵", pinyin: "wēi rú lěi luǎn", defZh: "比喻形势非常危险，像堆起来的蛋一样容易倒塌。", defEn: "Precarious as stacked eggs / Extremely dangerous", defBm: "Sangat bahaya", example: "当时局势危如累卵，稍有不慎就会全盘皆输。" },
    { word: "鱼跃龙门", pinyin: "yú yuè lóng mén", defZh: "比喻取得重大成功或地位大大提升。", defEn: "Leap over the dragon gate / Achieve great success", defBm: "Mencapai kejayaan besar", example: "他通过自己的努力，终于鱼跃龙门，考上了理想的大学。" },
    { word: "前功尽弃", pinyin: "qián gōng jìn qì", defZh: "以前的努力全部白费。", defEn: "All previous efforts wasted", defBm: "Segala usaha sebelum ini sia-sia", example: "如果现在放弃，就会前功尽弃。" },
    { word: "依样画葫芦", pinyin: "yī yàng huà hú lu", defZh: "比喻照着样子模仿，缺乏创新。", defEn: "Copy mechanically / Imitate blindly", defBm: "Meniru bulat-bulat", example: "学习不能只是依样画葫芦，还要懂得灵活运用。" },
    { word: "功败垂成", pinyin: "gōng bài chuí chéng", defZh: "事情快要成功时却失败了。", defEn: "Fail when success is near", defBm: "Gagal di saat akhir", example: "他在最后关头失误，功败垂成，令人惋惜。" },
    { word: "大功告成", pinyin: "dà gōng gào chéng", defZh: "巨大的工程或任务顺利完成。", defEn: "Accomplished / Successfully completed", defBm: "Berjaya diselesaikan", example: "经过几个月的努力，这项工程终于大功告成。" },
    { word: "独树一帜", pinyin: "dú shù yī zhì", defZh: "比喻自成一家，风格独特。", defEn: "Develop one's own unique style", defBm: "Mempunyai gaya tersendiri", example: "他的画风独树一帜，深受收藏家的喜爱。" },
    { word: "安居乐业", pinyin: "ān jū lè yè", defZh: "安定地生活，愉快地工作。", defEn: "Live and work in peace and contentment", defBm: "Hidup aman dan bekerja dengan tenang", example: "国家太平，百姓安居乐业。" },
    { word: "戛然而止", pinyin: "jiá rán ér zhǐ", defZh: "声音突然停止。", defEn: "Stop abruptly", defBm: "Terhenti secara tiba-tiba", example: "音乐戛然而止，全场一片寂静。" },
    { word: "居高临下", pinyin: "jū gāo lín xià", defZh: "占据高处，俯视下方，形容处于有利地位。", defEn: "Look down from a high position / Commanding position", defBm: "Berada di tempat tinggi", example: "他站在山顶，居高临下，俯瞰整个城市。" },
    { word: "心旷神怡", pinyin: "xīn kuàng shén yí", defZh: "心情舒畅，精神愉快。", defEn: "Relaxed and joyful / Refreshed", defBm: "Hati tenang dan gembira", example: "站在海边，迎着微风，令人心旷神怡。" }
];

// 将数据暴露为全局变量
var allIdioms = vocabularyData;
